version: "3.8"
services:
  mysqldb_local:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=XMchallenge_db
      - TZ=UTC
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: