spring:
  datasource:
    url: 'jdbc:mysql://localhost:3308/XMchallenge_db'
    username: root
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  mvc:
    date-format: yyyy-MM-dd
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
management:
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
springdoc:
  packagesToScan: com.kevag4.XMchallenge
  pathsToMatch: /api/**
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: .*
    rate-limits:
    - bandwidths:
      - capacity: 60
        time: 1
        unit: minutes
      expression: getRemoteAddr()